version: '1.0'
name: fetch1
displayName: fetch1
triggers:
  trigger: auto
  schedule:
    - cron: '* * */2 * * ? *'
stages:
  - name: fetchurl
    displayName: fetchurl
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: fetchurl
        displayName: fetchurl
        nodeVersion: 21.5.0
        commands:
          - npm install -g pnpm
          - pnpm install
          - pnpm electron:build:linux
          - cd release
          - ls
        strategy:
          retry: '0'
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: release
        version: 1.0.0.0
        autoIncrement: true
        strategy:
          retry: '0'
